In [1]:
import numpy as np

In [13]:
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [6]:
# get dimension
a.ndim

1

In [8]:
b = np.array([[9,6,5],[3,2,9]])
print(b)
b.ndim 

[[9 6 5]
 [3 2 9]]


2

In [10]:
# get shape
a.shape
b.shape

(2, 3)

In [16]:
# get type
a.dtype

dtype('int16')

In [17]:
# get size
a.itemsize #(16 bit of a)

2

In [18]:
b.itemsize

4

In [20]:
# get total size
# a.size * a.itemsize
a.nbytes

6

In [21]:
#accessing/changing specific elements,rows,columns

a = np.array([[1,2,3,4,5,6,7],[8,9,0,11,21,32,33]])
print(a)

In [27]:
a = np.array([[1,2,3,4,5,6,7],[8,9,0,11,21,32,32]]) 
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9  0 11 21 32 32]]


In [28]:
a.shape

(2, 7)

In [29]:
# get a specific element [r,c]
a[1,3]

11

In [31]:
# get a specific row
a[1, :]

array([ 8,  9,  0, 11, 21, 32, 32])

In [32]:
# get a specific column
a[: , 3]

array([ 4, 11])

In [35]:
# getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]  # // 6 replace with -1

array([2, 4, 6])

In [38]:
a[1,3] = 99 #replace the original element with new element
print(a)

a[:,3] = [5,10] # or only 5
print(a)

[[ 1  2  3  5  5  6  7]
 [ 8  9  0 99 21 32 32]]
[[ 1  2  3  5  5  6  7]
 [ 8  9  0 10 21 32 32]]


In [39]:
3D - example

SyntaxError: invalid syntax (3272422385.py, line 1)

In [41]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) 
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
# get specific element (work outside in)
b[0,1,1]
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [53]:
# replace 
b[:,1,:] = [[8,8],[9,9]]

In [52]:
b

array([[[1, 2],
        [8, 8]],

       [[5, 6],
        [9, 9]]])

##### Initializing different type of arrays

In [62]:
# all 0s matrix
np.zeros((2,3,))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
# all 1s matrix
np.ones((4,2,3), dtype = 'int16')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [69]:
# any other number
np.full((2,2),55, dtype = 'float32')

array([[55., 55.],
       [55., 55.]], dtype=float32)

In [70]:
np.full((2,2),55)

array([[55, 55],
       [55, 55]])

In [74]:
# any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [75]:
print(a)

[[ 1  2  3  5  5  6  7]
 [ 8  9  0 10 21 32 32]]


In [76]:
# Random decimal number
np.random.rand(4,2)

array([[0.15398517, 0.12356149],
       [0.94243131, 0.15639065],
       [0.90034197, 0.50399022],
       [0.85718512, 0.28246163]])

In [77]:
np.random.random_sample(a.shape)

array([[0.5950876 , 0.88448821, 0.35448489, 0.37769455, 0.50536016,
        0.89879804, 0.15613178],
       [0.80690593, 0.06932487, 0.31964885, 0.36151143, 0.49925383,
        0.3939504 , 0.95791046]])

In [83]:
# Random integer values
np.random.randint(9,15, size =(3,3))

array([[13,  9, 12],
       [10, 10, 10],
       [ 9, 14, 12]])

In [84]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [92]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


##### create a pattern



In [122]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print (z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying array!!!

In [104]:
a = np.array([1,2,3])
b = a.copy() #using copying function to create reference of a
b

array([1, 2, 3])

In [105]:
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


# Mathematics
for more knowlwdge vist the link:
https://numpy.org/doc/stable/reference/routines.math.html

In [106]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [107]:
a + 2

array([3, 4, 5, 6])

In [108]:
a - 2

array([-1,  0,  1,  2])

In [109]:
a * 6

array([ 6, 12, 18, 24])

In [110]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [111]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [112]:
a ** 3 #( ** use for power)

array([ 1,  8, 27, 64], dtype=int32)

In [113]:
# take the sin
np.sin(a)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [114]:
print(a)

[1 2 3 4]


In [115]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

# Linear Algebra

In [119]:
a = np.ones((2,3))
print(a)

b= np.full((3,2),2)
print(b)

np.matmul(a,b) # matrix multiplication

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [121]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)


1.0

##### for more knowlwdge of Linear Algebra vist the link: https://numpy.org/doc/stable/reference/routines.linalg.html

# Statistics

In [123]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
np.min(stats)

1

In [125]:
np.min(stats,axis=1)

array([1, 4])

In [127]:
np.max(stats)

6

In [129]:
np.sum(stats, axis=0)

array([5, 7, 9])

#####  axis = 0 (means Vertical in matrix )  
axis = 1 (means Horizontal in matrix -->)

# Reorganizing Arrays

In [130]:
before = np.array([[9,6,5],[3,2,9]])
print(before)

[[9 6 5]
 [3 2 9]]


In [131]:
print(before.shape)

(2, 3)


In [135]:
before = np.array([[9,6,5],[3,2,4]])
print(before)

after = before.reshape((3,2))
print(after)

[[9 6 5]
 [3 2 4]]
[[9 6]
 [5 3]
 [2 4]]


In [139]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v2,v1,v2,v1])

array([[5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [140]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [141]:
h2

array([[0., 0.],
       [0., 0.]])

In [143]:
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

##### Load Data from File

In [189]:
filedata = np.genfromtxt('D:/Python/Numpy/data.txt', delimiter=',')
#filedata.astype('int32')
filedata = filedata.astype('int32')
print(filedata)
# array = np.loadtxt('D:/Python/Numpy/data.txt')

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### boolean masking and advance indexing

In [181]:
filedata > 20


array([[False, False,  True, False,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False,  True,  True, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [182]:
filedata[filedata >50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [183]:
## you can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,6]]

array([2, 4, 7])

In [186]:
np.any(filedata > 50, axis=0) # true if any column has data > 50

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [187]:
np.all(filedata > 50, axis=0) # true only when all element of column > 50

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [188]:
((filedata > 50 ) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [190]:
(~(filedata > 50 ) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

##### Ritik Singh
##### Kiit University
Date: 17/02/2023